### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by elfmimi** [majbthrd/nuc_driver#1]
This repository is flawed from lack of proper license.

**Comment by majbthrd** [comment]
As stated in the README.md, this repository is merely a copy of Nuvoton reference code staged for convenience to use with TinyUSB.  I can hardly assert a particular license on someone else's source code.  Please take up your concerns with the authors of this code; the links are already provided in the README.md.

**Comment by elfmimi** [comment]
I was not expecting this to be closed without solving.
I wanted you to act on behalf of others including me to convince Nuvoton to have proper license included in their release.

**Comment by majbthrd** [comment]
I can see that [you have previously asked Nuvoton](https://github.com/OpenNuvoton/NUC123BSP/issues/3) this question, and you were told:

> Basically, it is welcome to use them on Nuvoton products.
> We are working hard to come out an official license agreement for this.
> I think it will be friendly and could be able to apply to all Nuvoton MCU BSPs.

I have no connection to Nuvoton, nor any influence.  If you are not content with their answer to your question, you must continue contact them directly.
